version: '3'

volumes:
  test_postgres_data: {}
  test_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/test/django/Dockerfile
    image: sdap_test_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
    env_file:
      - ./.envs/.test/.django
      - ./.envs/.test/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: sdap_production_postgres
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
      - test_postgres_data_backups:/backups
    env_file:
      - ./.envs/.test/.postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: sdap_test_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: sdap_test_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: sdap_test_flower
    ports:
      - "5555:5555"
    command: /start-flower
