# Generated by Django 2.2.5 on 2019-09-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20190813_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondaEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('env_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tool',
            name='conda_environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='tools.CondaEnv'),
        ),
    ]
