# Generated by Django 2.2.5 on 2019-09-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20190925_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='command_line',
            new_name='script_file',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='conda_environment',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='path',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='script_name',
        ),
        migrations.DeleteModel(
            name='CondaEnv',
        ),
    ]
