# Generated by Django 2.2.5 on 2019-09-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20190924_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sep_type',
            field=models.CharField(choices=[('\t', 'Tab'), (',', 'Comma'), (';', 'Semicolon'), (' ', 'Space')], default=',', max_length=50),
        ),
    ]
